const data = [
    {
        id: 1,
        nombre: "Christoph Curly",
        marca: "Way in Bangkok City",
        precio: 14000,
        stock: 3,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJ2IXBbvmjtbrMjZSD8_-vtMcGUlrptkdYgw&usqp=CAU",
        category: "Urbana",
        description: "lorem lorem lorem lorem",
    },
    {
        id: 2,
        nombre: "Marixa Key",
        marca: "Bamboo Grove",
        precio: 15500,
        stock: 6,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn-TKO8CW9bUp2zhUzio09Kv9VvuArWvqYHs1PHm-idABMHke_UJuyxJhEEALZuP77xm0&usqp=CAU",
        category: "Natural",
        description: "lorem lorem lorem lorem",

    },
    {
        id: 3,
        nombre: "Jhon Ridick",
        marca: "Beautiful Mountain",
        precio: 11500,
        stock: 8,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRS81ObcUkw9lktJMVLLZCbWlGKZbzrE21BJA&usqp=CAU",
        category: "Natural",
        description: "lorem lorem lorem lorem",
    },
    {
        id: 4,
        nombre: "Ramón Bolaños",
        marca: "Shot of crystal clear lake during sunny day",
        precio: 15600,
        stock: 2,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3ZNXhk1UQeGl5pldZOvitNwiGGJJnmslWz-y1h-RppRRz-7d00Rh6hX9dxsSu6DqpeOg&usqp=CAU",
        category: "Natural",
        description: "lorem lorem lorem lorem",
    },
    {
        id: 5,
        nombre: "Giannina Carlone",
        marca: "Tree in the midlle of FIeld covered with beautiful grass",
        precio: 19500,
        stock: 5,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBK613v6WtMwXWSeD9PFBGPtQ9LNZCIPl68AvwR87AVIkZzSSLFdGuj-A-65P3sVP6HzU&usqp=CAU",
        category: "Natural",
        description: "lorem lorem lorem lorem",
    },
    {
        id: 6,
        nombre: "Pedro Perestrowsky",
        marca: "View of the plaza España",
        precio: 27500,
        stock: 2,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVKahiQqJ0hIOF6HCoFHhTR0wKKsKRog5ydAo4iMAqwPFrAzuArEgawT6X6xL1Nd6NTSc&usqp=CAU",
        category: "Urbana",
        description: "lorem lorem lorem lorem",
    },
    {
        id: 7,
        nombre: "Jerry Smith",
        marca: "Blurred traffic light trails on road",
        precio: 22750,
        stock: 3,
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZk66zQqkW649PzXSITFtYF_usU43Vj6IJcg&usqp=CAU",
        category: "Urbana",
        description: "lorem lorem lorem lorem",
    },
    {
        id: 8,
        nombre: "Martina Gómez",
        marca: "Lake surrounded by mointain",
        precio: 13500,
        stock: 4,
        img: "https://indufer.com.ar/wp-content/uploads/2018/07/martillo-carpintero-stanley-51271-D_NQ_NP_607618-MLV26988783339_032018-F-1.jpg",
        category: "Natural",
        description: "lorem lorem lorem lorem",
    },
    {
        id: 9,
        nombre: "Set Allen",
        marca: "Shot of modern architecture with skyscrapers",
        precio: 14800,
        stock: 5,
        img: "https://http2.mlstatic.com/D_NQ_NP_742149-MLA31020578768_062019-O.webp",
        category: "Urbana",
        description: "lorem lorem lorem lorem",
    },
    {
        id: 10,
        nombre: "Sofia Malvares",
        marca: "Ajuntament in Valencia Spain",
        precio: 16500,
        stock: 5,
        img: "https://http2.mlstatic.com/D_NQ_NP_802135-MLA43195892556_082020-O.webp",
        category: "Urbana",
        description: "lorem lorem lorem lorem",
    },
    {
        id: 11,
        nombre: "Rudolf Frankchrteken",
        marca: "Rocky mountains covered with snow in Alaska",
        precio: 22700,
        stock: 3,
        img: "https://www.demaquinasyherramientas.com/wp-content/uploads/2017/02/Bahco-Arco-de-sierra-junior.jpg",
        category: "Natural",
        description: "lorem lorem lorem lorem", 
    },
    {
        id: 12,
        nombre: "Rita Cervantes",
        marca: "Grayscale shot of bridges",
        precio: 11800,
        stock: 5,
        img: "https://www.sinergiaindustrial.com.ar/images/AC5391E22E744CF8A474C376EE16A637.jpg",
        category: "Urbana",
        description: "lorem lorem lorem lorem",
    }
    
];


module.exports = { 
    data,
}